In [42]:
#연관규칙분석 실습

In [43]:
import mlxtend
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [44]:
dataset = [
    ['Milk', 'Cookie', 'Apple', 'Beans', 'Eggs', 'Yogurt'],
    ['Coke', 'Cookie', 'Apple', 'Beans', 'Eggs', 'Yogurt'],
    ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
    ['Milk', 'Orange', 'Corn', 'Beans', 'Yogurt'],
    ['Corn', 'Cookie', 'Cookie', 'Beans', 'Ice cream', 'Eggs']
]

In [45]:
type(dataset)

list

In [46]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [47]:
te = TransactionEncoder()

In [48]:
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[ True,  True, False,  True, False,  True, False, False,  True,
        False,  True],
       [ True,  True,  True,  True, False,  True, False, False, False,
        False,  True],
       [ True, False, False, False, False,  True, False,  True,  True,
        False, False],
       [False,  True, False, False,  True, False, False, False,  True,
         True,  True],
       [False,  True, False,  True,  True,  True,  True, False, False,
        False, False]])

In [49]:
df = pd.DataFrame(te_ary, columns = te.columns_)

In [50]:
df

,Apple,Beans,Coke,Cookie,Corn,Eggs,Ice cream,Kidney Beans,Milk,Orange,Yogurt
0,True,True,False,True,False,True,False,False,True,False,True
1,True,True,True,True,False,True,False,False,False,False,True
2,True,False,False,False,False,True,False,True,True,False,False
3,False,True,False,False,True,False,False,False,True,True,True
4,False,True,False,True,True,True,True,False,False,False,False

In [51]:
#mlxtend의 Apriori 알고리즘 
from mlxtend.frequent_patterns import association_rules
apriori(df, min_support = 0.6)

    support   itemsets
0       0.6        (0)
1       0.8        (1)
2       0.6        (3)
3       0.8        (5)
4       0.6        (8)
5       0.6       (10)
6       0.6     (0, 5)
7       0.6     (1, 3)
8       0.6     (1, 5)
9       0.6    (1, 10)
10      0.6     (3, 5)
11      0.6  (1, 3, 5)

In [52]:
apriori(df, min_support = 0.6, use_colnames = True)

    support               itemsets
0       0.6                (Apple)
1       0.8                (Beans)
2       0.6               (Cookie)
3       0.8                 (Eggs)
4       0.6                 (Milk)
5       0.6               (Yogurt)
6       0.6          (Apple, Eggs)
7       0.6        (Cookie, Beans)
8       0.6          (Beans, Eggs)
9       0.6        (Beans, Yogurt)
10      0.6         (Cookie, Eggs)
11      0.6  (Cookie, Beans, Eggs)

In [53]:
#결과 필터링해보기

In [54]:
frequent_itemsets = apriori = apriori(df, min_support = 0.6, use_colnames = True)

In [55]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x:len(x))

In [56]:
frequent_itemsets

    support               itemsets  length
0       0.6                (Apple)       1
1       0.8                (Beans)       1
2       0.6               (Cookie)       1
3       0.8                 (Eggs)       1
4       0.6                 (Milk)       1
5       0.6               (Yogurt)       1
6       0.6          (Apple, Eggs)       2
7       0.6        (Cookie, Beans)       2
8       0.6          (Beans, Eggs)       2
9       0.6        (Beans, Yogurt)       2
10      0.6         (Cookie, Eggs)       2
11      0.6  (Cookie, Beans, Eggs)       3

In [58]:
frequent_itemsets[(frequent_itemsets['length'] == 2) & (frequent_itemsets['support']>= 0.6)]

    support         itemsets  length
6       0.6    (Apple, Eggs)       2
7       0.6  (Cookie, Beans)       2
8       0.6    (Beans, Eggs)       2
9       0.6  (Beans, Yogurt)       2
10      0.6   (Cookie, Eggs)       2

In [59]:
#연관규칙분석결과에서 confidence, lift 등 조건에 맞는 패턴 찾기

In [62]:
rules = association_rules(frequent_itemsets, metric = "confidence", min_threshold = 0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Apple),(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,(Eggs),(Apple),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,(Cookie),(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
3,(Beans),(Cookie),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875
4,(Beans),(Eggs),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,(Eggs),(Beans),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,(Beans),(Yogurt),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875
7,(Yogurt),(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
8,(Cookie),(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
9,(Eggs),(Cookie),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875
10,"(Cookie, Beans)",(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
11,"(Cookie, Eggs)",(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.50,0.75,1.000,0.875
12,"(Beans, Eggs)",(Cookie),0.6,0.6,0.6,1.00,1.666667,1.0,0.24,inf,1.00,1.00,1.000,1.000
13,(Cookie),"(Beans, Eggs)",0.6,0.6,0.6,1.00,1.666667,1.0,0.24,inf,1.00,1.00,1.000,1.000
14,(Beans),"(Cookie, Eggs)",0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875
15,(Eggs),"(Cookie, Beans)",0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.00,0.75,0.375,0.875

In [64]:
rules2 = association_rules(frequent_itemsets, metric = "lift", min_threshold = 1.2)
rules2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Apple),(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
1,(Eggs),(Apple),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875
2,(Cookie),(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
3,(Beans),(Cookie),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875
4,(Beans),(Yogurt),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875
5,(Yogurt),(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
6,(Cookie),(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
7,(Eggs),(Cookie),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875
8,"(Cookie, Beans)",(Eggs),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
9,"(Cookie, Eggs)",(Beans),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.5,0.75,1.000,0.875
10,"(Beans, Eggs)",(Cookie),0.6,0.6,0.6,1.00,1.666667,1.0,0.24,inf,1.0,1.00,1.000,1.000
11,(Cookie),"(Beans, Eggs)",0.6,0.6,0.6,1.00,1.666667,1.0,0.24,inf,1.0,1.00,1.000,1.000
12,(Beans),"(Cookie, Eggs)",0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875
13,(Eggs),"(Cookie, Beans)",0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.0,0.75,0.375,0.875

In [66]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))

In [67]:
rules[(rules['antecedent_len'] >= 2) & (rules['confidence'] > 0.75) & (rules['lift'] > 1.2)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len
10,"(Cookie, Beans)",(Eggs),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875,2
11,"(Cookie, Eggs)",(Beans),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875,2
12,"(Beans, Eggs)",(Cookie),0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.0,1.00,1.0,1.000,2